# Generated by Django 3.1.8 on 2021-07-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210705_1012'),
        ('customers', '0002_auto_20210705_1342'),
    ]

    operations = [
    ]
