# Generated by Django 3.1.8 on 2021-07-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210707_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_suspended',
        ),
    ]
